#!/bin/sh -e

#
# bat - get battery capacity and status.
#       author: https://github.com/dylanaraps
#

bat_dir=/sys/class/power_supply/BAT0

read -r capacity < "$bat_dir/capacity"
read -r status   < "$bat_dir/status"

printf '%s%% (%s)\n' "$capacity" "$status"
