#!/bin/sh

#
# bri - brightness control
#

command -v xbacklight >/dev/null || {
    printf '%s: %s\n' "${0##*/}" "Please install 'xbacklight'."
    exit 1
}

if [ -z "$1" ]; then
  xbacklight -get
elif [ "$1" -gt 100 ]; then
  xbacklight -set 100
elif [ "$1" -lt 5 ]; then
  xbacklight -set 5
else
  xbacklight -set "$1"
fi
