#!/bin/sh
#
# Control brightness with xbacklight.
#
# Usage: bri, bri [5-100]

command -v xbacklight >/dev/null || {
    printf 'err: %s\n' "command 'xbacklight' not found."
    exit 1
}

if [ -z "$1" ]; then
  xbacklight -get
elif [ "$1" -gt 100 ]; then
  xbacklight -set 100
elif [ "$1" -lt 5 ]; then
  xbacklight -set 5
else
  xbacklight -set "$1"
fi
