#!/bin/sh

#
# cky - conky
#

# shellcheck disable=SC1090
[ -f ~/.cache/rpg/colors ] && . ~/.cache/rpg/colors

printf '%s' "$(cat << CONF
conky.config = {
    alignment = 'bottom_middle',
    background = true,
    default_color = '${color0:=#000000}',
    double_buffer = true,
    font = 'SF Mono:size=26:style=bold',
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    gap_x = 0,
    gap_y = 30,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = false,
    own_window_type = 'desktop',
    own_window_transparent = true,
    update_interval = 10,
    use_xft = true,
    uppercase = false,
}

conky.text = [[
\${time %H:%M}  \${wireless_essid wlp2s0}  \${battery_percent}%
]];
CONF
)" > ~/.conkyrc

killall -q conky

while pgrep -x conky > /dev/null; do
    sleep 1;
done

conky -c ~/.conkyrc -d
