#!/bin/sh

#
# cky - conky
#

killall -q conky

# shellcheck disable=SC1090
[ -f ~/.cache/rpg/colors ] && . ~/.cache/rpg/colors

printf '%s' "$(cat << CONF
conky.config = {
    alignment = 'top_left',
    background = true,
    default_color = '${color0:-"#000000"}',
    double_buffer = true,
    font = 'Roboto Mono:size=30:style=medium',
    font2 = 'Roboto Mono:size=90:style=medium',
    font3 = 'IcoFont:size=28:style=regular',
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    gap_x = 130,
    gap_y = 110,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = false,
    own_window_type = 'override',
    own_window_title = 'conky',
    own_window_class = 'Conky',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    update_interval = 30,
    use_xft = true,
    uppercase = false,
}

conky.text = [[
\${font2}\${time %H:%M}\${font}
\${time %A %d %B}

\${voffset 5}\${font3} \${voffset -5}\${font}\${execi 3600 curl wttr.in/Stockholm?format="%C+%t+%h+%p\n"}
\${voffset 5}\${font3} \${voffset -5}\${font}\${wireless_essid wlp2s0}
\${voffset 5}\${font3} \${voffset -5}\${font}\${battery_percent}%
]];
CONF
)" > ~/.conkyrc

while pgrep -x conky > /dev/null; do (:;:); done

conky -c ~/.conkyrc -d
