#!/bin/sh

[ -f "$HOME/.cache/pal/colors" ] && {
    # shellcheck disable=SC1090
    . "$HOME/.cache/pal/colors"

    # shellcheck disable=SC2154
    dmenu_run -i -p "launch:" \
        -nb "$color0" \
        -nf "$color15" \
        -sb "$color1" \
        -sf "$color15" \
        -fn "RobotoMono-28"
}

