#!/bin/sh

# shellcheck disable=1090
[ -f ~/.cache/colors/colors ] && . ~/.cache/colors/colors

dmenu_run -i \
    -nb "${color8:=#777777}" \
    -nf "${color0:=#000000}" \
    -sb "${color8:=#777777}" \
    -sf "${color15:=#FFFFFF}" \
    -fn "SFMono-28"
