#!/bin/sh

# shellcheck disable=SC1090
[ -f ~/.cache/rpg/colors ] && . ~/.cache/rpg/colors

dmenu_run -i \
    -nb "${color8:=#777777}" \
    -nf "${color0:=#000000}" \
    -sb "${color8:=#777777}" \
    -sf "${color15:=#FFFFFF}" \
    -fn "JetBrainsMono-28"
