#!/bin/sh

#
# drt - dirty directory
#

log() {
    printf '%s: %s\n' "$1" "${2##*/}"
}

for dir in ~/github/bin \
    ~/projects/bymates \
    ~/projects/jackieshop \
    ~/packages/st \
    ~/packages/sowm \
    ~/dotfiles \
    ~/.vim/plugged/cs.vim \
    ~/.vim/plugged/sl.vim \
    ~/github/cpr \
    ~/github/todo \
    ~/github/typography \
    ~/github/onemoresalary \
    ~/github/fehawen-files \
    ~/github/lipp \
    ~/github/rpg; do
    (
        [ -d $dir ] || {
            log "nodir" "$dir"
        }

        cd $dir 2> /dev/null || exit

        command git rev-parse --is-inside-work-tree 1> /dev/null 2> /dev/null || {
            log "nogit" "$dir"
            exit
        }

        [ -z "$(git status --short 2> /dev/null)" ] || log "dirty" "$dir"
    )
done
