#!/bin/sh

#
# drt - dirty directory
#

log() {
    printf '%s -> %s\n' "$1" "${2##*/}"
}

printf '\n'

for dir in ~/github/bin \
    ~/github/cpr \
    ~/dotfiles \
    ~/github/rpg; do
    (
        [ -d $dir ] || {
            log "nodir" "$dir"
        }

        cd $dir 2> /dev/null || exit

        command git rev-parse --is-inside-work-tree 1> /dev/null 2> /dev/null || {
            log "nogit" "$dir"
            exit
        }

        if [ -z "$(git status --short 2> /dev/null)" ]; then
            log "clean" "$dir"
        else
            log "dirty" "$dir"
        fi
    )
done

printf '\n'
