#!/bin/sh

#
# loc
#

[ -f "$1" ] || exit 1

while IFS= read -r line || [ -n "$line" ]; do
    all=$((all+1))
    [ -z "$line" ] || {
        lines=$((lines+1))
    }
done < "$1"

prin() {
    printf '%7s %s\n' "$1" "$2"
}

printf 'Number of lines in: %s\n' "$1"
prin "$lines" "(without empty lines)"
prin "$all" "(with empty lines)"
