#!/bin/sh
#
# Generate colorscheme with wal and set wallpaper
#
# Usage: luv, luv [image directory path], luv [image file path]

arg=${1:-"$HOME/pictures/tranquility"}

wal -i "$arg" -n

command -v xsetroot >/dev/null && {
    # shellcheck disable=SC1090
    [ -f ~/.cache/wal/colors.sh ] && . ~/.cache/wal/colors.sh

    # shellcheck disable=SC2154
    xsetroot -solid "$color1"
}
