#!/bin/sh

[ "$1" ] || {
    printf 'No name for new shell executable provided.\n'
    exit 1
}

[ -f "$1" ] && {
    printf 'File %s already exists.\n' "'$1'"
    exit 1
}

shebang='#!/bin/sh'

[ "$2" = "bash" ] && {
    shebang='#!/usr/bin/env bash'
}

printf '%s\n\n#\n# %s\n#' "$shebang" "$1" > "$1"
chmod +x "$1"

[ -z "$EDITOR" ] && {
    printf 'Unable to open file %s, EDITOR not set.\n' "'$1'"
    exit
}

$EDITOR "$1"
