#!/bin/sh

#
# Set output to external monitor(s).
#

# Usage: mon, mon [auto]

command -v xrandr >/dev/null || {
    printf 'err: command "xrandr" not found.\n'
    exit 1
}

[ "$1" = "auto" ] && {
    xrandr --auto
    exit 0
}

log() {
    printf 'Using display(s): %s\n' "$*"
}

dpy_a="$(xrandr | grep "primary" | awk '{print $1}')"
dpy_b="$(xrandr | grep -w "connected" | awk '{if(NR>1)print $1}' | head -1)"
dpy_c="$(xrandr | grep -w "connected" | awk '{if(NR>2)print $1}' | head -1)"
dpy_d="$(xrandr | grep -w "connected" | awk '{if(NR>3)print $1}' | head -1)"

if [ -n "$dpy_b" ] && [ -n "$dpy_c" ] && [ -n "$dpy_d" ]; then
    log "$dpy_b" "$dpy_c" "$dpy_d"

    xrandr \
        --output "$dpy_a" --off \
        --output "$dpy_b" --auto \
        --output "$dpy_c" --auto --right-of "$dpy_b" \
        --output "$dpy_d" --auto --right-of "$dpy_c"
elif [ -n "$dpy_b" ] && [ -n "$dpy_c" ]; then
    log "$dpy_b" "$dpy_c"

    xrandr \
        --output "$dpy_a" --off \
        --output "$dpy_b" --auto \
        --output "$dpy_c" --auto --right-of "$dpy_b"
elif [ -n "$dpy_b" ]; then
    log "$dpy_b"

    xrandr \
        --output "$dpy_a" --off \
        --output "$dpy_b" --auto
else
    log "$dpy_a [internal/auto]"
  xrandr --auto
fi
