#!/bin/sh

#
# pal
#

[ "$1" = "dark" ] && {
    rpg d 1> /dev/null 2> /dev/null
    cky 1> /dev/null 2> /dev/null
}

[ "$1" = "light" ] && {
    rpg l 1> /dev/null 2> /dev/null
    cky 1> /dev/null 2> /dev/null
}
