#!/bin/sh

#
# rnm - rename all files in a dir
#
# example: rnm ~/wallpapers wall_
# result:  rename all files to wall_[index].[extension]

[ -d "$1" ] || {
    printf 'Not a directory: %s\n' "$1"
    exit 1
}

[ "$2" ] || {
    printf 'Second arg for name required\n'
    exit 1
}

dir=$1
new=$2

(
    cd "$dir" > /dev/null || {
        printf 'Failed to change directory to: %s\n' "$1"
        exit 1
    }

    set +f
    set -f -- *

    for file in "$@"; do
        i=$((i+1))
        [ -f "$file" ] && mv -fv "$file" "${new}${i}.${file##*\.}"
    done
)
