#!/bin/sh

#
# rpg - random palette generator
#

add_sequence() {
    seqs="$seqs]$1;$2\\";

    case $1 in
        *";"*)
            [ "${1##*;}" -lt 16 ] && {
                printf '%s\n' "color${1##*;}=\"$2\"" >> "$cache_dir/colors"
            }
        ;;
    esac
}

hex() {
    set -f

    # shellcheck disable=SC2046

    set -- $(shuf -i "$1"-"$2" -n 3)

    printf '#%02x%02x%02x\n' "$1" "$2" "$3"

    set +f
}

print_palette() {
    for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
        printf '\033[38;5;%sm⬛\033[m' "$i"

        [ "$i" = 7 ] && printf '\n'
    done

    printf '\n'

    exit
}

main() {
    export LC_ALL=C

    mkdir -p "${cache_dir:=${HOME}/.cache/rpg}"

    case $1 in
        d|dark) mode=1 ;;
        l|light) mode=2 ;;
        r|reload) cat "$cache_dir/sequences" 2>/dev/null; exit ;;
        c|current) print_palette ;;
        *) printf '%s\n' \
            "Usage: rpg [OPTION]" \
            "d, dark       Generate a random dark palette" \
            "l, light      Generate a random light palette" \
            "r, reload     Reload current palette" \
            "c, current    Print current palette"
            exit
        ;;
    esac

    min="$((mode > 1 ? 80 : 110))"
    max="$((mode > 1 ? 160 : 190))"
    bg="$(hex "$((mode > 1 ? 235 : 20))" "$((mode > 1 ? 245 : 30))")"
    fg="$(hex "$((mode > 1 ? 15 : 205))" "$((mode > 1 ? 55 : 245))")"
    black="$(hex "$((mode > 1 ? 100 : 80))" "$((mode > 1 ? 120 : 100))")"
    red="$(hex "$min" "$max")"
    green="$(hex "$min" "$max")"
    yellow="$(hex "$min" "$max")"
    blue="$(hex "$min" "$max")"
    magenta="$(hex "$min" "$max")"
    cyan="$(hex "$min" "$max")"

    :> "$cache_dir/colors"

    add_sequence "4;0" "$bg"
    add_sequence "4;1" "$red"
    add_sequence "4;2" "$green"
    add_sequence "4;3" "$yellow"
    add_sequence "4;4" "$blue"
    add_sequence "4;5" "$magenta"
    add_sequence "4;6" "$cyan"
    add_sequence "4;7" "$fg"
    add_sequence "4;8" "$black"
    add_sequence "4;9" "$red"
    add_sequence "4;10" "$green"
    add_sequence "4;11" "$yellow"
    add_sequence "4;12" "$blue"
    add_sequence "4;13" "$magenta"
    add_sequence "4;14" "$cyan"
    add_sequence "4;15" "$fg"
    add_sequence "4;232" "$bg"
    add_sequence "11" "$bg"
    add_sequence "10" "$fg"
    add_sequence "12" "$fg"
    add_sequence "13" "$fg"
    add_sequence "19" "$bg"
    add_sequence "4;256" "$fg"

    [ "$VTE_VERSION" ] || add_sequence "708" "$bg"

    command -v xsetroot >/dev/null && xsetroot -solid "$black"

    for tty in /dev/pts/[0-9]*; do
        [ -w "$tty" ] && printf %b "$seqs" > "$tty" &
    done

    printf %b "$seqs" > "$cache_dir/sequences"

    print_palette
}

main "$@"
