#!/bin/sh -f

#
# shee - A poor implementation of `tree` in plain `sh`, with colored output.
#

die() {
    printf '%s\n' "$@"
    exit 1
}

log() {
    indent="${3:-"├─ "}"

    [ "$depth" -gt "0" ] && {
        i=0

        while [ "$i" -lt "$depth" ]; do
            indent="│  $indent"
            i=$((i + 1))
        done
    }

    printf '\033[90m%s\033[%sm%s\033[m\n' "$indent" "${2:-"39"}" "$1"
}

loop() {
    cur=${1%%/}
    depth=$((depth + 1))
    last_depth=$depth

    [ -d "$cur" ] || die "Not a directory: $cur"

    set +f
    set -f -- "$cur"/* "$cur"/.*

    for entity in "$@"; do
        case ${entity##*/} in
            .|..) ;;
            *)
                [ -f "$entity" ] && [ -z "$dirs_only" ] && files="$entity:$files"
                [ -d "$entity" ] && dirs="$entity:$dirs"
            ;;
        esac
    done

    if [ -n "$files" ]; then
        # shellcheck disable=2086
        {
            IFS=:
            set +f
            set -f -- $files
            unset IFS
            unset files
        }

        for file do
            log "${file##*/}" "$file_color"
        done
    elif [ "$dirs_only" ]; then
        last_depth="$((last_depth - 1))"
    fi

    [ -n "$dirs" ] && {
        # shellcheck disable=2086
        {
            IFS=:
            set +f
            set -f -- $dirs
            unset IFS
            unset dirs
        }

        for dir do
            log "${dir##*/}/" "$dir_color"
            loop "$dir" "$dir_color"
        done
    }

    depth=$((depth - 1))
}

usage() {
printf %s "\
Usage: ${0##*/} [OPTION]... [DIRECTORY]...
A poor implementation of \`tree\` in plain \`sh\`, with colored output.

With no DIRECTORY, default to using \`\$PWD\`.

  -d, --dirs-only          only show directories in output
  -h, --help               display this help and exit
"
exit
}

main() {
    depth=0
    last_depth=0
    dir_color="1;34"
    file_color="33"

    case $1 in
        '-h'|'--help') usage ;;
        '-d'|'--dirs-only') dirs_only=1; target=$2 ;;
        *) target=$1 ;;
    esac

    [ "$target" ] || target="$PWD"
    [ -d "$target" ] || die "Not a directory: $target"

    log "${target##*/}/" "$dir_color" "┌─ "
    loop "$target"

    n=0
    end="└"

    while [ "$n" -lt "$last_depth" ]; do
        n=$((n + 1))

        if [ "$n" -eq "$last_depth" ]; then
            end="$end──┘"
        else
            end="$end──┴"
        fi
    done

    printf '\033[90m%s\033[m\n' "$end"
}

main "$@"
