#!/bin/sh

#
# sqh - reset current git branch, specifying [base] for merge-base branch
#       usage: sqh [base]
#

[ "$1" ] || exit 1

branch="$(git rev-parse --abbrev-ref HEAD)"

read -r "Reset branch '$branch' using merge-base branch '$1'? [y/N] " answer

if [ "$answer" != "y" ]; then
    printf 'Declined...\nExiting.\n'
    exit 0
else
    git reset "$(git merge-base "$1" "$branch")"
fi
