#!/bin/sh

xinitrc() {
    [ -f ~/.Xresources ] && xrdb -merge ~/.Xresources &

    shw init &

    xset b off
    xset +fp ~/.fonts
    setxkbmap -layout se &

    exec sowm
}

trap "DISPLAY=:0 xinitrc" USR1

(
    trap '' USR1

    exec Xorg \
        -ardelay 250 \
        -arinterval 25 \
        -nolisten tcp \
        :0 vt1
) &

wait
