#!/bin/sh

xinitrc() {
    export DISPLAY=:0

    [ -f ~/.Xresources ] && xrdb -merge ~/.Xresources &

    # shellcheck disable=SC1090
    [ -f ~/.cache/rpg/colors ] && . ~/.cache/rpg/colors &

    xsetroot -solid "${color8:=#777777}"

    xset +fp ~/.fonts

    setxkbmap -layout se &

    exec sowm
}

trap xinitrc USR1

(
    trap '' USR1

    exec X -ardelay 250 \
        -arinterval 25 \
        -nolisten tcp \
        -keeptty \
        :0 vt1 -quiet
) &

wait
