#!/bin/sh

xinitrc() {
    [ -f ~/.Xresources ] && xrdb -merge ~/.Xresources &

    xsetroot -solid "#252831"

    xset +fp ~/.fonts

    xset b off

    setxkbmap -layout se &

    exec sowm
}

trap 'DISPLAY=:0 xinitrc' USR1

(
    trap '' USR1

    exec Xorg \
        -ardelay 250 \
        -arinterval 25 \
        -nolisten tcp \
        :0 vt1
) &

wait
