#!/bin/sh

#
# tdo - todo helper
#

cd_or_exit() {
    cd "$TODO_DIR" || exit 1
}

todo_push() {
    (
        cd_or_exit

        git add .
        git commit -m "Bump @ $(date '+%Y/%m/%d %H:%M')"
        git push
    )
}

todo_pull() {
    (
        cd_or_exit
        git pull
    )
}

todo_read() {
    less "$todo_file"
}

todo_edit() {
    vim "$todo_file"
}

main() {
    case $1 in
        push) opt="push" ;;
        pull) opt="pull" ;;
        read) opt="read" ;;
        edit) opt="edit" ;;
    esac

    [ -z "$opt" ] && {
        printf "Usage: tdo push|pull|read|edit\n"
        exit
    }

    [ -z "$TODO_DIR" ] && {
        printf "TODO_DIR is not set.\n"
        exit 1
    }

    todo_file=${TODO_DIR%%/}/TODO

    [ -f "$todo_file" ] || {
        printf "No 'TODO' file found in TODO_DIR.\n"
        exit 1
    }

    todo_"$opt"
}

main "$@"
