#!/bin/sh

#
# vol - volume control
#

command -v pamixer >/dev/null || {
    printf '%s: %s\n' "${0##*/}" "Please install 'pamixer'."
    exit 1
}

if [ -z "$1" ]; then
  pamixer --get-volume-human
elif [ "$1" -gt 100 ]; then
  pamixer --set-volume 100
elif [ "$1" -lt 1 ]; then
  pamixer --set-volume 1
else
  pamixer --set-volume "$1"
fi
