#!/bin/sh

#
# ytd - youtube-dl
#

case $1 in
    a|audio)
        yt-dlp \
            --add-metadata \
            -f "bestaudio[ext=m4a]" \
            -o "$HOME/media/music/%(title)s.%(ext)s" \
            "$2"

        exit
    ;;
    v|video)
        yt-dlp \
            -f "bestvideo[ext=mp4][height<1200]+bestaudio[ext=m4a]/best[ext=mp4][height<1200]/best" \
            -o "$HOME/media/video/%(title)s.%(ext)s" \
            "$2"

        exit
    ;;
    *)
        printf 'Usage: ytd a|audio|v|video url\n'
        exit
    ;;
esac
